# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DP_Colorbar_BD/DP_Colorbar_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DP_Colorbar_BD || ORIG_REF_NAME==DP_Colorbar_BD} -quiet] -quiet

# IP: bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DP_Colorbar_BD_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==DP_Colorbar_BD_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: d:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.gen/sources_1/bd/DP_Colorbar_BD/DP_Colorbar_BD_ooc.xdc
