# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.srcs/sources_1/bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'DP_Colorbar_BD_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.gen/sources_1/bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DP_Colorbar_BD_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.gen/sources_1/bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DP_Colorbar_BD_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.srcs/sources_1/bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'DP_Colorbar_BD_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.gen/sources_1/bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DP_Colorbar_BD_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Zynq_Pro/DP_Colorbar20240402/DP_Colorbar/DP_Colorbar.gen/sources_1/bd/DP_Colorbar_BD/ip/DP_Colorbar_BD_zynq_ultra_ps_e_0_0/DP_Colorbar_BD_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DP_Colorbar_BD_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
